--- # Bootstrap servers
- hosts: servers
  remote_user: krolik
  become: yes
  tasks:
    - name: install openssl with var
      apt:
        update_cache: yes
        name: "{{ target_app }}"
        state: latest
