--- # Bootstrap servers
- hosts: servers
  become: yes
  tasks:
    - name: install MC and openssl
      apt:
        update_cache: yes
        name:
          - mc
          - openssl
        state: latest
    - name: create a file
      file:
        name: /home/krolik/test.txt
        state: touch
    - name:
      lineinfile:
        line: "Przykladowy tekst"
        path: /home/krolik/test.txt
